export const ACTION_STYLES = [
  ".actions{min-width:0;padding:16px 20px 20px}",
  ".actions-head{display:flex;align-items:baseline;gap:10px}",
  ".actions-head h2{flex:1}",
  ".action-list{display:flex;flex-direction:column;gap:8px;margin-top:12px}",
  ".action{padding:4px 12px 8px;border:1px solid var(--color-line);border-radius:14px}",
  ".action-head{display:flex;align-items:flex-start;gap:6px}",
  ".action-text{flex:1;min-width:0;padding-top:6px;font-weight:700;overflow-wrap:anywhere}",
  ".action .more{order:0;margin-right:-6px}",
  ".carried{padding-top:8px;font-size:12px;font-weight:700;color:var(--color-ink-faint)}",
  ".action.done .action-text{color:var(--color-ink-faint);text-decoration:line-through}",
  ".unowned{padding-top:4px;font-size:13px;color:var(--color-ink-faint)}",
  ".sheet-title{font-size:15px;font-weight:700}",
  ".actions.deciding{box-shadow:0 0 0 1px var(--color-accent),var(--shadow-rest)}",
  ".sources{display:flex;flex-wrap:wrap;gap:4px;margin-top:6px}",
  ".sources li{min-width:0;max-width:100%}",
  ".src{display:flex;align-items:center;gap:6px;max-width:100%;min-height:24px;padding:0 8px 0 6px;border:1px solid var(--color-line);border-radius:999px;background:transparent;color:var(--color-ink-soft);font-size:12px;line-height:16px;transition:background-color .15s}",
  ".src:hover{background:var(--color-felt-deep)}",
  ".src svg{width:12px;height:12px;color:var(--hue)}",
  ".src span{max-width:24ch;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".action .person{padding:4px 0 0}",
  ".actions .empty{margin-top:8px}",
  ".action-foot{margin-top:16px;padding-top:16px;border-top:1px solid var(--color-line)}",
  ".action-form{display:flex;flex-wrap:wrap;align-items:flex-end;gap:8px}",
  ".stack{display:flex;flex-direction:column;gap:4px;flex:1 1 12rem;min-width:0}",
  ".stack.narrow{flex:0 1 11rem}",
  // Wide enough for the poker room's split: the lanes, and the actions beside them.
  "@media (min-width:1200px){.main{grid-template-columns:minmax(0,1fr) 300px}.actions{position:sticky;top:20px;align-self:start;max-height:calc(100vh - 40px);overflow-y:auto}.action-form{flex-flow:column nowrap;align-items:stretch}.stack,.stack.narrow{flex:none}.action-form .btn{align-self:flex-start}}",

  ".dock{position:fixed;z-index:2;left:0;right:0;bottom:0;display:flex;flex-direction:column;align-items:center;gap:8px;padding:0 12px 12px;pointer-events:none}",
  ".toast,.select-bar{pointer-events:auto}",
  ".select-bar{display:flex;flex-wrap:wrap;align-items:center;gap:8px 12px;width:100%;max-width:44rem;padding:12px 16px;background:var(--color-surface);border:1px solid var(--color-line);border-radius:20px;box-shadow:var(--shadow-lift)}",
  ".select-info{flex:1 1 100%;display:flex;flex-wrap:wrap;align-items:baseline;gap:0 8px;min-width:0}",
  "@media (min-width:640px){.select-info{flex:1 1 12rem}}",
  ".select-count{font-weight:700}",
  ".select-name{flex:1 1 6rem;min-width:0}",
  ".toast{max-width:34rem;padding:12px 24px;border:1px solid var(--color-line);border-radius:22px;background:var(--color-surface-hi);box-shadow:var(--shadow-lift);font-weight:700;text-align:center;text-wrap:pretty}",
];

