export const POPOVER_STYLES = [
  // Menus and sheets float in one layer that scrolls with the page.
  ".layer{position:absolute;top:0;left:0;z-index:3}",
  ".pop{position:absolute;width:max-content;max-width:calc(100vw - 16px);max-height:calc(100vh - 16px);overflow-y:auto;overscroll-behavior:contain;border:1px solid var(--color-line);border-radius:14px;background:var(--color-surface-hi);box-shadow:var(--shadow-lift);transform-origin:0 0}",
  // A menu: a short title, rows with an icon and a shortcut, a strip of
  // four small buttons for the order, and the one row that cannot be taken
  // back alone under a rule, in the stop color.
  ".menu{display:flex;flex-direction:column;min-width:15rem;padding:6px}",
  ".menu-item{flex:none;display:flex;align-items:center;gap:10px;min-height:32px;padding:0 10px;border:0;border-radius:8px;background:transparent;color:var(--color-ink);text-align:left}",
  ".menu-item svg,.menu-gap{flex:none;width:16px;color:var(--color-ink-soft)}",
  ".menu-item .w{flex:1;min-width:0;overflow-wrap:anywhere}",
  ".menu-item:hover,.menu-item:focus-visible,.strip button:hover,.strip button:focus-visible{background:var(--color-felt-deep)}",
  ".menu-item:focus-visible{outline-offset:-2px}",
  '.menu-item[aria-disabled="true"],.menu-item[aria-disabled="true"] svg{color:var(--color-ink-faint)}',
  // The words take the ink the Delete buttons take, which holds its
  // contrast in the dark theme too; the icon is the stop color itself.
  ".menu-item.danger{color:color-mix(in srgb,var(--color-stop) 75%,var(--color-ink))}.menu-item.danger svg{color:var(--color-stop)}",
  ".menu-item.danger:hover,.menu-item.danger:focus-visible{background:color-mix(in srgb,var(--color-stop) 12%,var(--color-surface-hi))}",
  ".menu-item.back{font-weight:700}",
  ".menu-done{display:none}",
  ".keys,.menu-kind{font:11px/16px var(--mono);color:var(--color-ink-faint)}",
  ".menu-kind{color:var(--color-ink-soft)}",
  ".sep{flex:none;height:1px;margin:6px 4px;background:var(--color-line)}",
  ".strip{flex:none;display:flex;align-items:center;gap:4px;min-height:36px;padding:0 4px 0 10px}",
  ".strip .w{flex:1;display:flex;flex-direction:column}",
  ".strip .w .keys{line-height:14px}",
  ".strip button{display:grid;place-items:center;width:32px;height:32px;padding:0;border:1px solid var(--color-line-strong);border-radius:8px;background:transparent;color:var(--color-ink)}",
  '.strip button[aria-disabled="true"]{color:var(--color-ink-faint);border-color:var(--color-line)}',
  // The list of a note's stickers, in the menu's language: one line each.
  ".st-sheet{width:20rem;gap:0;padding:6px}",
  ".st-list{display:flex;flex-direction:column;max-height:16rem;overflow-y:auto}",
  ".st-list li{display:flex;align-items:center;gap:8px;min-height:36px;padding:0 4px 0 10px}",
  ".st-list .st.small{width:24px;height:24px}",
  ".st-list .w{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".st-do{flex:none;display:grid;place-items:center;width:32px;height:32px;padding:0;border:0;border-radius:8px;background:transparent;color:var(--color-ink-soft)}",
  ".st-do:hover,.st-do:focus-visible{background:var(--color-felt-deep);color:var(--color-ink)}",
  ".st-do.danger{color:var(--color-stop)}",
  ".st-sheet .off-why{max-width:none;padding-top:6px}",
  ".off-why{max-width:15rem;padding:2px 10px 6px;font-size:12px;line-height:16px;color:var(--color-ink-soft)}",
  ".sheet{display:flex;flex-direction:column;gap:10px;width:20rem;padding:14px}",
  ".sheet .row .field{flex:1 1 4rem;padding:5px 10px}",
  // A sheet is a column: its fields take the height they need, no more.
  ".sheet .stack{flex:none}",
  ".menu-title{max-width:15rem;padding:6px 10px 4px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}",
  ".menu-note{max-width:15rem;padding:4px 10px 6px}",
  // The sticker book: two sheets of the same seven, with what they mean
  // written once, between them.
  ".st.small,.st.px.small{position:static;flex:none;width:28px;height:28px;margin:0;pointer-events:none}",
  ".book-pop{width:372px;gap:8px;padding:12px}",
  ".book-head{display:flex;align-items:center;justify-content:space-between;gap:8px}",
  ".left3{display:inline-flex;align-items:center;gap:5px;font-size:12px;color:var(--color-ink-soft)}",
  ".left3 i{width:8px;height:8px;border:1.5px solid var(--color-line-strong);border-radius:50%}",
  ".left3 i.have{border-color:var(--color-accent);background:var(--color-accent)}",
  ".book{padding:6px;border-radius:12px;background:var(--color-felt);box-shadow:var(--shadow-well)}",
  ".leaf{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));padding:4px 0;border:1px solid transparent;border-radius:9px}",
  ".leaf.active{border-color:var(--color-line);background:var(--color-surface-hi)}",
  ".set{display:flex;align-items:center;gap:6px;padding:2px 6px}",
  ".set kbd,.spine kbd{font:10px/12px var(--mono);color:var(--color-ink-faint)}",
  ".set kbd{padding:0 4px;border:1px solid var(--color-line-strong);border-radius:4px}",
  ".set .on{display:none;color:var(--color-accent)}",
  ".set.active .on{display:inline}",
  ".choice{display:grid;place-items:center;height:50px;padding:0;border:0;border-radius:9px;background:transparent}",
  ".choice .st,.choice .st.px{position:static;margin:0;pointer-events:none}",
  ".choice:hover{background:var(--color-felt-deep)}",
  ".choice:hover .st svg{translate:0 -3px;scale:1.08}",
  ".choice:focus-visible{outline-offset:-2px}",
  ".choice:disabled{opacity:.4}",
  ".spine{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));padding:3px 0;font-size:10.5px;line-height:13px;text-align:center;color:var(--color-ink-soft);text-wrap:balance}",
  ".spine span{display:flex;flex-direction:column;align-items:center;padding:0 1px}",
  ".scrim{display:none}",
  ".from{padding:6px 10px;border-radius:8px;background:var(--color-felt-deep);color:var(--color-ink-soft);font-size:13px;overflow-wrap:anywhere}",
  ".link-list{display:flex;flex-direction:column;gap:6px;max-height:10rem;overflow-y:auto}",
  ".link-list li{display:flex;flex-wrap:wrap;align-items:center;gap:8px}",
  ".link-list span{flex:1 1 5rem;min-width:0;overflow-wrap:anywhere}",
];

